language: cpp
distro: trusty
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-6 cmake libboost-dev libboost-system-dev libboost-date-time-dev libboost-regex-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest
