language: cpp
dist: xenial

addons:
    apt:
        packages:
            - cmake-data
            - cmake
            - libboost-dev
            - libboost-system-dev

compiler: clang


cache:
            apt: true
            ccache: true
                    
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - clang-3.7
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"


before_install:
    - eval "${MATRIX_EVAL}"

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest
