language: cpp
distro: xenial

addons:
    apt:
        packages:
            - cmake-data
            - cmake
            - boost-dev
            - boost-system-dev

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc

before_install:
    - eval "${MATRIX_EVAL}"

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./test/testjsring
