language: cpp
distro: xenial

addons:
    apt:
        sources:
            - llvm-toolchain-xenial-5.0
        packages:
            - cmake-data
            - cmake
            - libboost-dev
            - libboost-system-dev
            - clang-5.0

matrix:
  include:
    - os: linux
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

  #- os: linux
  #compiler: gcc

before_install:
    - eval "${MATRIX_EVAL}"

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./test/testjsring
